
IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
   KOKKOS_FIND_IMPORTED(KokkosCUDA INTERFACE
    IMPORTED_NAME Kokkos::CUDA
    LIBRARIES cudart cuda
    LIBRARY_PATHS ${KOKKOS_CUDA_DIR}/lib64 ENV LD_LIBRARY_PATH ENV CUDA_PATH
   )
ELSE()
   KOKKOS_CREATE_IMPORTED_TPL(Kokkos::CUDA INTERFACE
    LINK_LIBRARIES cuda
   )
ENDIF()

