
IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
   KOKKOS_FIND_IMPORTED(CUDA 
    LIBRARIES cudart cuda
    LIBRARY_PATHS ${KOKKOS_CUDA_DIR}/lib64 ENV LD_LIBRARY_PATH ENV PATH 
   )
ELSE()
   KOKKOS_FIND_IMPORTED(CUDA 
    LIBRARIES cuda
    LIBRARY_PATHS ${KOKKOS_CUDA_DIR}/lib64 ENV LD_LIBRARY_PATH ENV PATH 
   )
ENDIF()

