
TRY_COMPILE(KOKKOS_HAS_PTHREAD_ARG
  ${KOKKOS_TOP_BUILD_DIR}/tpl_tests
  ${KOKKOS_SOURCE_DIR}/cmake/compile_tests/pthread.cpp
  LINK_LIBRARIES -pthread
  COMPILE_DEFINITIONS -pthread)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(${NAME} DEFAULT_MSG ${KOKKOS_HAS_PTHREAD_ARG})

SET(PTHREAD_COMPILE_OPTIONS -pthread)
SET(PTHREAD_LINK_OPTIONS    -pthread)

KOKKOS_CREATE_IMPORTED_TPL(PTHREAD
  COMPILE_OPTIONS -pthread
  LINK_OPTIONS    -pthread)



